/*
 * bnkconv.c - offline converter: Ad Lib OPL3.BNK -> the driver's 4-operator overlay.
 *
 * The driver plays General MIDI through the DDK's compiled-in 2-operator patch bank
 * (glpPatch). This tool reads the Ad Lib "Accomp. Bank" OPL3.BNK, which carries 471 named
 * timbres of which 157 are genuine 4-operator instruments (plan/0009/four-op-reference.md),
 * and emits fmbank4op.h: a 128-entry General-MIDI overlay. Where a program has a 4-operator
 * match, the overlay carries a converted noteStruct and the driver programs a 4-operator
 * voice; otherwise the driver falls back to the 2-operator glpPatch entry.
 *
 * This is a build-time host tool, not kernel code. It runs offline (the driver build under
 * Wine does not run it); its output fmbank4op.h is committed and compiled into the driver.
 *   cc -Wall -Werror -o bnkconv bnkconv.c && ./bnkconv OPL3.BNK > ../fmbank4op.h
 *
 * The record layout is the toolkit's FM.ASM preset format: four operators of six bytes each
 * (registers 20h,40h,60h,80h,E0h,spare), a connect byte (D0 = first-channel CNT, D3-D1 =
 * feedback, D7 = second-channel CNT), a type byte (0x08 = 4-operator), a transpose byte, a
 * spare. The program-to-timbre mapping is by instrument keyword, the one curation choice, and
 * the audible result is attested on hardware.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define BNK_NUM      471
#define BNK_NAMEOFF  0x12C
#define BNK_RECOFF   0x34B0
#define BNK_NAMESZ   28
#define BNK_RECSZ    28
#define TYPE_4OP     0x08

/* PATCH_??? markers, mirrored from fmsynth.h so the emitted header needs no other include. */
#define PATCH_1_4OP  0
#define PATCH_1_2OP  2

/* General MIDI melodic programs 0..127, each a keyword matched against a timbre name. An
 * empty string leaves that program 2-operator (no 4-op override). */
static const char *gGmKeyword[128] = {
    "piano","piano","piano","honky","epiano","epiano","harpsi","clav",
    "celesta","glock","musicbox","vibes","marimba","xylo","bells","dulcimer",
    "organ","organ","organ","church","reed","accordn","harmonica","tango",
    "guitar","guitar","guitar","guitar","guitar","guitmute","guitover","guitdist",
    "bass","bass","bass","fretless","slapbass","slapbass","synbass","synbass",
    "violin","viola","cello","contra","strings","strings","harp","timpani",
    "strings","strings","synstr","synstr","choir","choir","voice","orchit",
    "trumpet","trombone","tuba","mutetrp","horn","brass","synbras","synbras",
    "sax","sax","sax","sax","oboe","enghorn","bassoon","clarinet",
    "picc","flute","recorder","panflute","bottle","shakuh","whistle","ocarina",
    "square","sawwave","calliope","chiff","charang","voxlead","fifths","basslead",
    "newage","warm","poly","choir","bowed","metal","halo","sweep",
    "rain","sound","crystal","atmos","bright","goblin","echo","scifi",
    "sitar","banjo","shamisen","koto","kalimba","bagpipe","fiddle","shanai",
    "tinkle","agogo","steeldrm","wood","taiko","tom","syndrum","revcym",
    "guitfret","breath","seashore","bird","phone","copter","applause","gunshot"
};

/* Lower-case a copy of s in place, for case-insensitive matching. */
static void lower(char *s)
{
    for (; *s; s++)
        if (*s >= 'A' && *s <= 'Z') *s += 32;
}

int main(int argc, char **argv)
{
    if (argc < 2) { fprintf(stderr, "usage: %s OPL3.BNK\n", argv[0]); return 2; }

    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror("open"); return 2; }
    static unsigned char d[65536];
    size_t n = fread(d, 1, sizeof(d), f);
    fclose(f);
    if (n < (size_t)(BNK_RECOFF + BNK_NUM * BNK_RECSZ)) {
        fprintf(stderr, "short file: %lu bytes\n", (unsigned long)n);
        return 2;
    }

    /* Collect the timbre names (lower-cased, prefix stripped) and their record offsets. */
    static char name[BNK_NUM][16];
    static int  is4op[BNK_NUM];
    int i;
    for (i = 0; i < BNK_NUM; i++) {
        const unsigned char *e = d + BNK_NAMEOFF + i * BNK_NAMESZ;
        char raw[13];
        memcpy(raw, e, 12); raw[12] = 0;
        /* strip a leading "O3_" bank prefix if present */
        const char *base = raw;
        if (strncmp(raw, "O3_", 3) == 0) base += 3;
        strncpy(name[i], base, sizeof(name[i]) - 1);
        name[i][sizeof(name[i]) - 1] = 0;
        lower(name[i]);
        is4op[i] = (d[BNK_RECOFF + i * BNK_RECSZ + 25] == TYPE_4OP);
    }

    printf("/* fmbank4op.h -- GENERATED by tools/bnkconv.c from OPL3.BNK. Do not edit.\n");
    printf(" * A 128-entry General MIDI overlay of 4-operator voices (plan/0009). A program\n");
    printf(" * with gGm4OpHas[program] set uses gGm4OpNote[program] and the driver programs a\n");
    printf(" * 4-operator voice; otherwise it falls back to the 2-operator glpPatch entry.\n");
    printf(" * The program-to-timbre mapping is attested on hardware. */\n");
    printf("#ifndef _FMBANK4OP_H_\n#define _FMBANK4OP_H_\n\n");

    static unsigned char has[128];
    printf("static const noteStruct gGm4OpNote[128] = {\n");
    int matched = 0;
    int prog;
    for (prog = 0; prog < 128; prog++) {
        int rec = -1;
        const char *kw = gGmKeyword[prog];
        if (kw && kw[0]) {
            for (i = 0; i < BNK_NUM; i++)
                if (is4op[i] && strstr(name[i], kw)) { rec = i; break; }
        }
        if (rec < 0) {
            /* No 4-operator match: emit a zero entry the driver never reads. */
            printf("  { {{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0},{0,0,0,0,0}}, {0,0},{0,0},{0,0}, %d, 0 },  /* %d: 2-op fallback */\n",
                   PATCH_1_2OP, prog);
            has[prog] = 0;
            continue;
        }
        has[prog] = 1; matched++;
        const unsigned char *r = d + BNK_RECOFF + rec * BNK_RECSZ;
        printf("  { {");
        int op;
        for (op = 0; op < 4; op++) {
            const unsigned char *o = r + op * 6;
            printf("{0x%02x,0x%02x,0x%02x,0x%02x,0x%02x}%s",
                   o[0], o[1], o[2], o[3], o[4], op < 3 ? "," : "");
        }
        /* connect byte: D3-D0 (FB + first CNT) -> C0; D7 (second CNT) -> C3. The OPL3 enables
         * a voice's output only through the STL/STR bits (D5/D4 = 0x30) of each C-register,
         * exactly as the 2-op glpPatch bank bakes them in; the driver's note path masks these
         * bits (for pan) but never sets them, so bake 0x30 into both C-registers here or the
         * 4-op voice is silent. */
        unsigned char c0 = (unsigned char)((r[24] & 0x0F) | 0x30);
        unsigned char c1 = (unsigned char)(((r[24] >> 7) & 1) | 0x30);
        printf("}, {0,0},{0,0},{0x%02x,0x%02x}, %d, 0 },  /* %d: %s */\n",
               c0, c1, PATCH_1_4OP, prog, name[rec]);
    }
    printf("};\n\n");

    printf("static const unsigned char gGm4OpHas[128] = {\n  ");
    for (prog = 0; prog < 128; prog++)
        printf("%d,%s", has[prog], (prog % 16 == 15) ? "\n  " : "");
    printf("\n};\n\n#endif /* _FMBANK4OP_H_ */\n");

    fprintf(stderr, "bnkconv: %d of 128 programs mapped to a 4-operator timbre\n", matched);
    return 0;
}
